unique_name: Products
object_type: dimension
label: Products
type: standard

hierarchies:

  - unique_name: Product Hierarchy
    label: Product Hierarchy

    levels:

      - unique_name: Level 02

      - unique_name: Level 03

      - unique_name: Level 04

      - unique_name: Products Level

level_attributes:

  - unique_name: Level 02
    label: Level 02
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID_LEVEL_1
    name_column: PRODUCT_CATEGORY_LEVEL_1

  - unique_name: Level 03
    label: Level 03
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID_LEVEL_2
    name_column: PRODUCT_CATEGORY_LEVEL_2

  - unique_name: Level 04
    label: Level 04
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID_LEVEL_3
    name_column: PRODUCT_CATEGORY_LEVEL_3

  - unique_name: Products Level
    label: Level 05
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID
    name_column: PRODUCT_CATEGORY
