unique_name: Product Service Hierarchy
object_type: dimension
label: Product Service Hierarchy
type: standard

hierarchies:

  - unique_name: Product Service Hierarchy Hierarchy
    label: Product Service Hierarchy Hierarchy

    levels:

      - unique_name: Product Service Hierarchy Level

        secondary_attributes:

          - unique_name: d_PRODUCT_SERVICE_GROUP_CODE
            label: PRODUCT_SERVICE_GROUP_CODE
            folder: Product Service Hierarchy Attributes
            dataset: Product_Service_Hierarchy.dataset
            key_columns:
              - PRODUCT_SERVICE_GROUP_CODE
            name_column: PRODUCT_SERVICE_GROUP_CODE
            sort_column: PRODUCT_SERVICE_GROUP_CODE
            allowed_calcs_for_dma:
              - Lag
              - Range
              - Siblings

          - unique_name: d_PRODUCT_SERVICE_GROUP_NAME
            label: PRODUCT_SERVICE_GROUP_NAME
            folder: Product Service Hierarchy Attributes
            dataset: Product_Service_Hierarchy.dataset
            key_columns:
              - PRODUCT_SERVICE_GROUP_NAME
            name_column: PRODUCT_SERVICE_GROUP_NAME
            sort_column: PRODUCT_SERVICE_GROUP_NAME
            allowed_calcs_for_dma:
              - Lag
              - Range
              - Siblings

          - unique_name: d_PRODUCT_SERVICE_NAME
            label: PRODUCT_SERVICE_NAME
            folder: Product Service Hierarchy Attributes
            dataset: Product_Service_Hierarchy.dataset
            key_columns:
              - PRODUCT_SERVICE_NAME
            name_column: PRODUCT_SERVICE_NAME
            sort_column: PRODUCT_SERVICE_NAME
            allowed_calcs_for_dma:
              - Lag
              - Range
              - Siblings

level_attributes:

  - unique_name: Product Service Hierarchy Level
    label: Product Service Hierarchy Level
    is_unique_key: true
    dataset: Product_Service_Hierarchy.dataset
    key_columns:
      - PRODUCT_SERVICE_HIERARCHY_CODE
    name_column: PRODUCT_SERVICE_HIERARCHY_CODE

modeler_metadata:
  version: "0"
  modified: "false"
