unique_name: Product Category
object_type: dimension
label: Product Category
type: standard

hierarchies:

  - unique_name: Product Category Hierarchy
    label: Product Category Hierarchy

    levels:

      - unique_name: Level 1

      - unique_name: Level 2

      - unique_name: Product Category Id Level 3

      - unique_name: Product Category Level

level_attributes:

  - unique_name: Level 1
    label: Level 2
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID_LEVEL_1
    name_column: PRODUCT_CATEGORY_LEVEL_1
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Lag
      - ParallelPeriod
      - Range
      - Siblings

  - unique_name: Level 2
    label: Level 3
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID_LEVEL_2
    name_column: PRODUCT_CATEGORY_LEVEL_2
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Lag
      - ParallelPeriod
      - Range
      - Siblings

  - unique_name: Product Category Id Level 3
    label: Level 4
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID_LEVEL_3
    name_column: PRODUCT_CATEGORY_LEVEL_3
    allowed_calcs_for_dma:
      - Ancestor
      - Descendants
      - Lag
      - ParallelPeriod
      - Range
      - Siblings

  - unique_name: Product Category Level
    label: Level 5
    dataset: VW_PRODUCT_CATEGORY.dataset
    key_columns:
      - PRODUCT_CATEGORY_ID
    name_column: PRODUCT_CATEGORY

modeler_metadata:
  version: "0"
  modified: "false"
