unique_name: Product_Service_Hierarchy.dataset
object_type: dataset
label: Product_Service_Hierarchy
connection_id: snowflake.connection
table: VW_PRODUCT_SERVICE_HIERARCHY
immutable: true

columns:
  - name: DW_FROM_DATE
    data_type: datetime
  - name: DW_IS_CURRENT
    data_type: boolean
  - name: DW_TO_DATE
    data_type: datetime
  - name: HK_PRODUCT_SERVICE_HIERARCHY
    data_type: string
  - name: PRODUCT_SERVICE_GROUP_CODE
    data_type: string
  - name: PRODUCT_SERVICE_GROUP_NAME
    data_type: string
  - name: PRODUCT_SERVICE_HIERARCHY_CODE
    data_type: string
  - name: PRODUCT_SERVICE_NAME
    data_type: string
